// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package sb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindInvalid-0]
	_ = x[KindMin-1]
	_ = x[KindArrayEnd-10]
	_ = x[KindObjectEnd-20]
	_ = x[KindMapEnd-25]
	_ = x[KindTupleEnd-27]
	_ = x[KindNil-30]
	_ = x[KindBool-40]
	_ = x[KindStringEnd-49]
	_ = x[KindString-50]
	_ = x[KindStringBegin-51]
	_ = x[KindBytesEnd-54]
	_ = x[KindBytes-55]
	_ = x[KindBytesBegin-56]
	_ = x[KindInt-60]
	_ = x[KindInt8-70]
	_ = x[KindInt16-80]
	_ = x[KindInt32-90]
	_ = x[KindInt64-100]
	_ = x[KindUint-110]
	_ = x[KindUint8-120]
	_ = x[KindUint16-130]
	_ = x[KindUint32-140]
	_ = x[KindUint64-150]
	_ = x[KindFloat32-160]
	_ = x[KindFloat64-170]
	_ = x[KindNaN-175]
	_ = x[KindArray-180]
	_ = x[KindObject-190]
	_ = x[KindMap-200]
	_ = x[KindTuple-210]
	_ = x[KindTypeName-230]
	_ = x[KindLiteral-240]
	_ = x[KindPointer-245]
	_ = x[KindRef-251]
	_ = x[KindMax-255]
}

const _Kind_name = "KindInvalidKindMinKindArrayEndKindObjectEndKindMapEndKindTupleEndKindNilKindBoolKindStringEndKindStringKindStringBeginKindBytesEndKindBytesKindBytesBeginKindIntKindInt8KindInt16KindInt32KindInt64KindUintKindUint8KindUint16KindUint32KindUint64KindFloat32KindFloat64KindNaNKindArrayKindObjectKindMapKindTupleKindTypeNameKindLiteralKindPointerKindRefKindMax"

var _Kind_map = map[Kind]string{
	0:   _Kind_name[0:11],
	1:   _Kind_name[11:18],
	10:  _Kind_name[18:30],
	20:  _Kind_name[30:43],
	25:  _Kind_name[43:53],
	27:  _Kind_name[53:65],
	30:  _Kind_name[65:72],
	40:  _Kind_name[72:80],
	49:  _Kind_name[80:93],
	50:  _Kind_name[93:103],
	51:  _Kind_name[103:118],
	54:  _Kind_name[118:130],
	55:  _Kind_name[130:139],
	56:  _Kind_name[139:153],
	60:  _Kind_name[153:160],
	70:  _Kind_name[160:168],
	80:  _Kind_name[168:177],
	90:  _Kind_name[177:186],
	100: _Kind_name[186:195],
	110: _Kind_name[195:203],
	120: _Kind_name[203:212],
	130: _Kind_name[212:222],
	140: _Kind_name[222:232],
	150: _Kind_name[232:242],
	160: _Kind_name[242:253],
	170: _Kind_name[253:264],
	175: _Kind_name[264:271],
	180: _Kind_name[271:280],
	190: _Kind_name[280:290],
	200: _Kind_name[290:297],
	210: _Kind_name[297:306],
	230: _Kind_name[306:318],
	240: _Kind_name[318:329],
	245: _Kind_name[329:340],
	251: _Kind_name[340:347],
	255: _Kind_name[347:354],
}

func (i Kind) String() string {
	if str, ok := _Kind_map[i]; ok {
		return str
	}
	return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
}
